# Generated by Django 6.0.1 on 2026-02-15 19:51

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoTrabalhador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Trabalhador')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('actualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de actualização')),
            ],
            options={
                'verbose_name': 'Classificação de trabalhador',
                'verbose_name_plural': 'Classificação dos trabalhador',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('actualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de actualização')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Género',
            },
        ),
        migrations.CreateModel(
            name='Incapacidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Incapacidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('actualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de actualização')),
            ],
            options={
                'verbose_name': 'Incapacidade',
                'verbose_name_plural': 'Incapacidade',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Província')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('actualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de actualização')),
            ],
            options={
                'verbose_name': 'Província',
                'verbose_name_plural': 'Província',
            },
        ),
        migrations.CreateModel(
            name='Razoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Razões de contracto de trabalho por tempo determinado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('actualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de actualização')),
            ],
            options={
                'verbose_name': 'Razões de contracto de trabalho por tempo determinado',
                'verbose_name_plural': 'Razões de contracto de trabalho por tempo determinado',
            },
        ),
        migrations.CreateModel(
            name='TipoAcidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Acidente de trabalho')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('actualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de actualização')),
            ],
            options={
                'verbose_name': 'Acidente de trabalho',
                'verbose_name_plural': 'Acidente de trabalho',
            },
        ),
        migrations.CreateModel(
            name='TipoContracto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('actualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de actualização')),
            ],
            options={
                'verbose_name': 'Contrato de trabalho',
                'verbose_name_plural': 'Contrato de trabalho',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Tipo de documento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('actualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de actualização')),
            ],
            options={
                'verbose_name': 'Documento de identidade',
                'verbose_name_plural': 'Documento de identidade',
            },
        ),
        migrations.CreateModel(
            name='Trabalhador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome do trabalhador')),
                ('nascimento', models.DateField(null=True, verbose_name='Data de nascimento')),
                ('pais', django_countries.fields.CountryField(max_length=2, null=True, verbose_name='País de origem')),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº de documento')),
                ('duracao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração(número de meses)')),
                ('doenca', models.BooleanField(default=False, verbose_name='Doença profissional')),
                ('custo_directo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custos directos em kz')),
                ('custo_indirecto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custos indirectos em kz')),
                ('capacidade_reduzida', models.BooleanField(default=False, verbose_name='Capacidade reduzida')),
                ('telefone', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefone')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Outras informações')),
                ('representante', models.BooleanField(default=False, verbose_name='Representante')),
                ('acidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trabalhadores.tipoacidente', verbose_name='Acidente de trabalho')),
                ('contracto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trabalhadores.tipocontracto', verbose_name='Contracto de trabalho')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trabalhadores.tipodocumento', verbose_name='Documento de identidade')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabalhadores', to='empresas.empresa')),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trabalhadores.genero', verbose_name='Género')),
                ('incapacidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trabalhadores.incapacidade', verbose_name='Incapacidade')),
                ('razoes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trabalhadores.razoes', verbose_name='Razões de contracto de trabalho por tempo determinado')),
                ('trabalhador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trabalhadores.classificacaotrabalhador', verbose_name='Trabalhador')),
            ],
            options={
                'verbose_name': 'Trabalhador',
                'verbose_name_plural': 'Trabalhador',
            },
        ),
    ]
