# Generated by Django 6.0.1 on 2026-02-15 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContraOrdenacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(verbose_name='Seleccione as contra-ordenações verificadas')),
                ('artigo', models.CharField(max_length=50, verbose_name='Artigo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('actualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de actualização')),
            ],
            options={
                'verbose_name': 'Contra-ordenação',
                'verbose_name_plural': 'Contra-ordenação',
            },
        ),
        migrations.CreateModel(
            name='ObjectivoInspeccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Objectivo da inspecção')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('actualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de actualização')),
            ],
            options={
                'verbose_name': 'Objectivo da inspecção',
                'verbose_name_plural': 'Objectivo da inspecção',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Província')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('actualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de actualização')),
            ],
            options={
                'verbose_name': 'Província',
                'verbose_name_plural': 'Província',
            },
        ),
        migrations.CreateModel(
            name='SectorEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Ramo económico')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('actualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de actualização')),
            ],
            options={
                'verbose_name': 'Sector económico',
                'verbose_name_plural': 'Sector económico',
            },
        ),
        migrations.CreateModel(
            name='TipoInspeccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Tipo de inspecção')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('actualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de actualização')),
            ],
            options={
                'verbose_name': 'Tipo de inspecção',
                'verbose_name_plural': 'Tipos de inspecção',
            },
        ),
        migrations.CreateModel(
            name='TipoPropriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Tipo de propriedade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('actualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de actualização')),
            ],
            options={
                'verbose_name': 'Tipo de propriedade',
                'verbose_name_plural': 'Tipo de propriedade',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('actualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de actualização')),
                ('data_inspeccao', models.DateField(verbose_name='Data inspectiva')),
                ('hora_inicio', models.TimeField(null=True, verbose_name='Hora de início da inspecção')),
                ('hora_termino', models.TimeField(null=True, verbose_name='Hora de término da inspecção')),
                ('nome', models.CharField(max_length=300, verbose_name='Designação da empresa')),
                ('nif', models.CharField(max_length=50, verbose_name='NIF da empresa')),
                ('telefone', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefone da empresa')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email da empresa')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Município')),
                ('distrito', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('rua', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rua')),
                ('documentos_analizados', models.TextField(blank=True, null=True, verbose_name='Documentos / aspectos analisados')),
                ('provas_colhidas', models.TextField(blank=True, null=True, verbose_name='Elementos de provas colhidos')),
                ('factos_constatados', models.TextField(blank=True, null=True, verbose_name='Factos constatados')),
                ('observacao_entidade_empregadora', models.TextField(blank=True, null=True, verbose_name='Observação da entidade empregadora')),
                ('conclusão', models.TextField(blank=True, null=True, verbose_name='Conclusão da inspecção')),
                ('prazo_regularizacao', models.IntegerField(blank=True, null=True, verbose_name='Prazo de regularização das contra-ordenações leves')),
                ('contra_ordenacoes', models.ManyToManyField(blank=True, to='empresas.contraordenacao', verbose_name='Contra-ordenações laborais')),
                ('objectivo_inspeccao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.objectivoinspeccao', verbose_name='Objectivo da inspecção')),
                ('provincia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.provincia', verbose_name='Província')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.sectoreconomico', verbose_name='Ramo económico')),
                ('tipo_inspeccao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.tipoinspeccao', verbose_name='Tipo inspecção')),
                ('propriedade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.tipopropriedade', verbose_name='Propriedade da Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
            },
        ),
    ]
